package cop5556fa18;

import static org.junit.Assert.assertEquals;

import java.io.FileOutputStream;
import java.io.OutputStream;
import java.lang.reflect.Method;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.ExpectedException;

import cop5556fa18.PLPAST.Program;
import cop5556fa18.PLPCodeGenUtils.DynamicClassLoader;

public class PLPCodeGenTest {	
	//determines whether show prints anything
		static boolean doPrint = true;
		
		static void show(Object s) {
			if (doPrint) {
				System.out.println(s);
			}
		}

		//determines whether a classfile is created
		static boolean doCreateFile = false;
		
		@Rule
		public ExpectedException thrown = ExpectedException.none();
		

		//values passed to CodeGenerator constructor to control grading and debugging output
		private boolean devel = true; //if true, print devel output
		private boolean grade = true; //if true, print grade output
		
		/**
		 * Generates bytecode for given input.
		 * Throws exceptions for Lexical, Syntax, and Type checking errors
		 * 
		 * @param input   String containing source code
		 * @return        Generated bytecode
		 * @throws Exception
		 */
		byte[] genCode(String input) throws Exception {
			
			//scan, parse, and type check
			PLPScanner scanner = new PLPScanner(input);
			show(input);
			scanner.scan();
			PLPParser parser = new PLPParser(scanner);
			Program program = parser.parse();
			PLPTypeChecker v = new PLPTypeChecker();
			program.visit(v, null);
//			show(program);  //It may be useful useful to show this here if code generation fails

			//generate code
			PLPCodeGen cv = new PLPCodeGen(null, devel, grade);
			byte[] bytecode = (byte[]) program.visit(cv, null);
			show(program); //doing it here shows the values filled in during code gen
			//display the generated bytecode
			show(PLPCodeGenUtils.bytecodeToString(bytecode));
			
			//write byte code to file 
			if (doCreateFile) {
				String name = ((Program) program).name;
				String classFileName = "bin/" + name + ".class";
				OutputStream output = new FileOutputStream(classFileName);
				output.write(bytecode);
				output.close();
				System.out.println("wrote classfile to " + classFileName);
			}
			
			//return generated classfile as byte array
			return bytecode;
		}
		
		/**
		 * Run main method in given class
		 * 
		 * @param className    
		 * @param bytecode    
		 * @param commandLineArgs  String array containing command line arguments, empty array if none
		 * @throws + 
		 * @throws Throwable 
		 */
		void runCode(String className, byte[] bytecode) throws Exception  {
			PLPRuntimeLog.initLog(); //initialize log used for grading.
			DynamicClassLoader loader = new DynamicClassLoader(Thread.currentThread().getContextClassLoader());
			Class<?> testClass = loader.define(className, bytecode);
			String[] commandLineArgs = {};
			@SuppressWarnings("rawtypes")
			Class[] argTypes = {commandLineArgs.getClass()};
			Method m = testClass.getMethod("main", argTypes );
			show("Output from " + m + ":");  //print name of method to be executed
			Object passedArgs[] = {commandLineArgs};//create array containing params, in this case a single array.
			//show(passedArgs);
			try {
			m.invoke(null, passedArgs);	
			}
			catch (Exception e) {
				Throwable cause = e.getCause();
				if (cause instanceof Exception) {
					Exception ec = (Exception) e.getCause();
					throw ec;
				}
				throw  e;
			}
		}
		
		/**
		 * Since we are not doing any optimization, the compiler will 
		 * still create a class with a main method and the JUnit test will
		 * execute it.  
		 * 
		 * The only thing it will do is append the "entering main" and "leaving main" messages to the log.
		 * 
		 * @throws Exception
		 */
	
		@Test
		public void emptyProg() throws Exception {
			String prog = "emptyProg";	
			String input = prog + "{}";
			byte[] bytecode = genCode(input);
			runCode(prog, bytecode);
			show("Log:\n "+PLPRuntimeLog.globalLog);
			assertEquals("entering main;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void integerLit() throws Exception {
			String prog = "intgegerLit";
			String input = prog + "{print 3;} ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;3;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		
		@Test
		public void dec0() throws Exception {
			String prog = "dec";
			String input = prog + "{int a= -3; int b=+4; print a+b; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;1;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void dec1() throws Exception {
			String prog = "dec";
			String input = prog + "{int a,b,c; a=1;b=2;c=3; print a+b+c; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;6;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void dec2() throws Exception {
			String prog = "dec";
			String input = prog + "{int a= 3; a=a+1; print a; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;4;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void condition0() throws Exception {
			String prog = "con";
			String input = prog + "{boolean c;c=true; if(c){print c;}; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;true;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void condition1() throws Exception {
			String prog = "con";
			String input = prog + "{int a=0; while(a<3){a=a+1;};print a; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;3;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void condition2() throws Exception {
			String prog = "con";
			String input = prog + "{boolean a=false; while(a!=true){a=true;};print a; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;true;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void fun0() throws Exception {
			String prog = "fun";
			String input = prog + "{float a=0.0; print sin(a); } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;0.0;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void fun1() throws Exception {
			String prog = "fun";
			String input = prog + "{float a=-1.2; print abs(a); } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;1.2;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void fun2() throws Exception {
			String prog = "fun";
			String input = prog + "{float a=2.4; print int(a); } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;2;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre0() throws Exception {
			String prog = "expr";
			String input = prog + "{string s1=\"abc\"; string s2 = \"def\"; print s1+s2; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;abcdef;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre1() throws Exception {
			String prog = "expr";
			String input = prog + "{string s1=\"abc\";string s3=\"ggg\"; string s2 = \"def\"; print s1+s2; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;abcdef;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre2() throws Exception {
			String prog = "expr";
			String input = prog + "{int a= 1;int b=2; int c=3; print a+c; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;4;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre3() throws Exception {
			String prog = "expr";
			String input = prog + "{int a= 1;a=a+1; print a<1; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;false;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre4() throws Exception {
			String prog = "expr";
			String input = prog + "{int a= 1;int b=2;int c=2; if(b==c|a==b){print a;}; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;1;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre5() throws Exception {
			String prog = "expr";
			String input = prog + "{int a= 1;int b=2;int c=2; if(b==c&a==b){print a;}; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre6() throws Exception {
			String prog = "expr";
			String input = prog + "{int a= 1;int b=6;print a&b; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;0;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre7() throws Exception {
			String prog = "expr";
			String input = prog + "{int a= 10000; a=1000; a= 100; print !a; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;-101;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre8() throws Exception {
			String prog = "expr";
			String input = prog + "{boolean a= false; print !a; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;true;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void expre9() throws Exception {
			String prog = "expr";
			String input = prog + "{print true > false; } ";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;true;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void failed0() throws Exception {
			String prog = "f0";
			String input = prog + "{print !false; print !true; print !(true | false); print !(true & false);}";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;true;false;false;true;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void failed00() throws Exception {
			String prog = "f0";
			String input = prog + "{print !false; print !true; print (true | false); print (true & false);}";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;true;false;true;false;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void failed1() throws Exception {
			String prog = "f1";
			String input = prog + "{int x; x = 1; if ( 2 == 3) {int x; x = 2; print x;}; print x;}";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;1;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void failed2() throws Exception {
			String prog = "f2";
			String input = prog + "{int x; x = 1; if ( 2 < 3) { int x; x = 2; print x;}; print x;}";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;2;1;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void failed3() throws Exception {
			String prog = "f3";
			String input = prog + "{print 4 ** 3 ** 2;}";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;262144;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
		@Test
		public void failed4() throws Exception {
			String prog = "f3";
			String input = prog + "{print 2.1 ** 1.2 ** 2;}";	
			byte[] bytecode = genCode(input);		
			runCode(prog, bytecode);	
			show("Log:\n"+PLPRuntimeLog.globalLog);
			assertEquals("entering main;2.9106889;leaving main;",PLPRuntimeLog.globalLog.toString());
		}
		
}
